Traceback [1;36m(most recent call last)[0m:
  File [0;32m"C:\PYTHON~2\lib\site-packages\BCPy2000\EmbeddedPythonConsole.py"[0m, line [0;32m233[0m, in [0;35m<module>[0m
    ReplaceStreams()
[1;36m  File [1;32m"C:\PYTHON~2\lib\site-packages\BCPy2000\EmbeddedPythonConsole.py"[1;36m, line [1;32m138[1;36m, in [1;35mReplaceStreams[1;36m[0m
[1;33m    IPython.core.ultratb.io.stdout = sys.stdout[0m
[1;31mAttributeError[0m[1;31m:[0m module 'IPython.core.ultratb' has no attribute 'io'
Traceback (most recent call last):
  File "C:\PYTHON~2\lib\site-packages\BCPy2000\EmbeddedPythonConsole.py", line 233, in <module>
    ReplaceStreams()
  File "C:\PYTHON~2\lib\site-packages\BCPy2000\EmbeddedPythonConsole.py", line 138, in ReplaceStreams
    IPython.core.ultratb.io.stdout = sys.stdout
AttributeError: module 'IPython.core.ultratb' has no attribute 'io'


